return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "luacheck",
      "shellcheck",
      "shfmt",
      "tailwindcss-language-server",
      "typescript-language-server",
      "css-lsp",
      "pyright",
      "json-lsp",
      "yaml-language-server",
      "dockerfile-language-server",
      "ansible-language-server",
      "sqlls",
      "tflint",
      "helm-ls",
      "prettier",
      "eslint_d",
      "black",
      "ruff-lsp",
    },
  },
}
