return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "gopls",
      "templ",
      "delve",
      "biome",
      "shellcheck",
      "shfmt",
      "tailwindcss-language-server",
      "html-lsp",
      "css-lsp",
      "pyright",
      "json-lsp",
      "yaml-language-server",
      "dockerfile-language-server",
      "sqlls",
      "emmet-language-server",
      "goimports",
      "gofumpt",
      "gomodifytags",
      "impl",
      "golangci-lint",
    },
  },
}
