return {
  "SmiteshP/nvim-navbuddy",
  event = "LspAttach",
  dependencies = {
    "neovim/nvim-lspconfig",
    "SmiteshP/nvim-navic",
    "MunifTanjim/nui.nvim",
  },
  config = function()
    local navbuddy = require("nvim-navbuddy")
    local actions = require("nvim-navbuddy.actions")

    navbuddy.setup({
      window = {
        border = "single",
        size = "75%",
        position = "50%",
        sections = {
          left = { size = "30%" },
          mid = { size = "40%" },
          right = { preview = "leaf" },
        },
      },
      node_markers = {
        enabled = true,
        icons = {
          leaf = "  ",
          leaf_selected = " → ",
          branch = " ",
        },
      },
      icons = {
        File = "󰈙 ",
        Module = " ",
        Namespace = "󰌗 ",
        Package = " ",
        Class = "󰌗 ",
        Method = "󰆧 ",
        Property = " ",
        Field = " ",
        Constructor = " ",
        Enum = "󰕘",
        Interface = "󰕘",
        Function = "󰊕 ",
        Variable = "󰆧 ",
        Constant = "󰏿 ",
        String = " ",
        Number = "󰎠 ",
        Boolean = "◩ ",
        Array = "󰅪 ",
        Object = "󰅩 ",
        Key = "󰌋 ",
        Null = "󰟢 ",
        EnumMember = " ",
        Struct = "󰌗 ",
        Event = " ",
        Operator = "󰆕 ",
        TypeParameter = "󰊄 ",
      },
      use_default_mappings = true,
      mappings = {
        ["<esc>"] = actions.close(),
        ["q"] = actions.close(),
        ["j"] = actions.next_sibling(),
        ["k"] = actions.previous_sibling(),
        ["h"] = actions.parent(),
        ["l"] = actions.children(),
        ["0"] = actions.root(),
        ["v"] = actions.visual_name(),
        ["V"] = actions.visual_scope(),
        ["y"] = actions.yank_name(),
        ["Y"] = actions.yank_scope(),
        ["i"] = actions.insert_name(),
        ["I"] = actions.insert_scope(),
        ["a"] = actions.append_name(),
        ["A"] = actions.append_scope(),
        ["r"] = actions.rename(),
        ["d"] = actions.delete(),
        ["f"] = actions.fold_create(),
        ["F"] = actions.fold_delete(),
        ["c"] = actions.comment(),
        ["<enter>"] = actions.select(),
        ["o"] = actions.select(),
        ["J"] = actions.move_down(),
        ["K"] = actions.move_up(),
        ["s"] = actions.toggle_preview(),
        ["<C-v>"] = actions.vsplit(),
        ["<C-s>"] = actions.hsplit(),
        ["g?"] = actions.help(),
      },
      lsp = {
        auto_attach = true,
        preference = nil,
      },
      source_buffer = {
        follow_node = true,
        highlight = true,
        reorient = "smart",
      },
      custom_hl_group = nil,
    })
  end,
}
