return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "json",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "html",
      "css",
      "markdown",
      "regex",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "query",
      "sql",
      "terraform",
      "nginx",
      "rust",
      "ron",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "templ",
    },
    query_linter = {
      enable = true,
      use_virtual_text = true,
      lint_events = { "BufWrite", "CursorHold" },
    },
  },
}
